### ISSUE TITLE
Dienst startet und bricht ab

### ISSUE THREAD

**Issue by xmasmc** [fiskaltrust/interface#2]
Habe versucht den Dienst fiskultrust zu starten mit test.cmd, der Dienst startet bricht aber ab.
Betriebssystem: Win7 64bit prof.
Muss vorher irgendetwas installiert werden ?

fiskaltrust -cashboxid=f9bb4d9f-db98-4c24-a614-87f9d874f0cc -test

**Folgende Meldung erfolgt:**
29.06.2016 07:29:48 CashBoxId auf "f9bb4d9f-db98-4c24-a614-87f9d874f0cc" gesetzt
29.06.2016 07:29:48 Try to load configuration from D:\download\Registrierkassen\Fiskaltrust_1\interface-master\tools\fiskaltrust-net40\configuration.json
29.06.2016 07:29:48 D:\download\Registrierkassen\Fiskaltrust_1\interface-master\tools\fiskaltrust-net40\configuration.json found
29.06.2016 07:29:48 Loading Helper Package fiskaltrust.service.helper.debug, Version 0.7.16150.577-beta
29.06.2016 07:29:48 Ein Teil des Pfades "C:\ProgramData\fiskaltrust\service\helpers\0.fiskaltrust.service.helper.debug\current\assemblies.txt" konnte nicht
 gefunden werden.
29.06.2016 07:29:48 Loading Helper Package fiskaltrust.service.helper.balancer, Version 0.7.16153.592-beta
29.06.2016 07:29:48 Ein Teil des Pfades "C:\ProgramData\fiskaltrust\service\helpers\1.fiskaltrust.service.helper.balancer\current\assemblies.txt" konnte ni
cht gefunden werden.
29.06.2016 07:29:48 Loading SecureSignaturCreationDevice Id 3d0e53b7-3f32-4f15-9328-74dba24ecbfd from Package fiskaltrust.signing.atrustonline, Version 0.8
.16147.550-dev
29.06.2016 07:29:48 Fehler beim starten des fiskaltrust.Service: Ein Teil des Pfades "C:\ProgramData\fiskaltrust\service\3d0e53b7-3f32-4f15-9328-74dba24ecb
fd\current\assemblies.txt" konnte nicht gefunden werden.

Unbehandelte Ausnahme: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\ProgramData\fiskaltrust\service\3d0e53b7-3f32-4f15-9328-74dba24ecbfd\c
urrent\assemblies.txt" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOpt
ions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Bo
olean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding)
   bei System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   bei fiskaltrust.service.launcher.ftService.internalStart(String[] args)
   bei fiskaltrust.service.launcher.Program.Main(String[] args)

**Comment by steininger** [comment]
Bitte das Verzeichnis "C:\ProgramData\fiskaltrust" löschen und erneut versuchen.
Hat der Rechner Internetzugriff? Scheinbar ist das Package nicht heruntergeladen worden.

**Comment by xmasmc** [comment]
Vielen Dank, das Verzeichnis löschen hat geholfen.
