### ISSUE TITLE
Queue is out of order,it has not been activated!

### ISSUE THREAD

**Issue by robertza** [fiskaltrust/interface#3]
hallo
wir haben alles laut doku installiert, beim startet test.cmd bekommen wir auch keine fehler, sobald wir versuchen einen beleg zu erstellen kommt folgende fehlermeldung.
27.01.2017 10:51:58 Queue e005a7cf-fc4b-4586-91b3-638a15cb9e53 is out of order,
it has not been activated!
wo liegt unser problem
anbei die einträge vom test.cmd

C:\Users\Administrator\Downloads\fiskaltrust.service.launcher(21)>"C:\Users\Admi
nistrator\Downloads\fiskaltrust.service.launcher(21)\fiskaltrust" -cashboxid=e0e
edb80-e96d-490e-b5c0-60420bcaf600  -accesstoken=BBnJxfRBFXSgzy5B0Rpx6FBDYqTgiU51
SXw117gZTZwNvNmMCL5Sv+Rs7rRpR9QVw1H9928DRHXEhwFqfpgIjac=  -test
27.01.2017 10:51:14 CashBoxId auf "e0eedb80-e96d-490e-b5c0-60420bcaf600" gesetzt

27.01.2017 10:51:14 AccessToken gesetzt
27.01.2017 10:51:14 Try to download configuration
27.01.2017 10:51:16 Downloading fiskaltrust.service.helper.helipad 1.0.16326.123
5 updates ....
27.01.2017 10:51:19 Download done!
27.01.2017 10:51:19 Downloading fiskaltrust.signing.atrustapdu 1.0.16326.1240 up
dates ....
27.01.2017 10:51:21 Download done!
27.01.2017 10:51:21 Downloading fiskaltrust.service.sqlite 1.0.16326.1233 update
s ....
27.01.2017 10:51:25 Download done!
27.01.2017 10:51:25 Rename fiskaltrust.service.helper.helipad 1.0.16326.1235 upd
ates ....
27.01.2017 10:51:25 Rename fiskaltrust.signing.atrustapdu 1.0.16326.1240 updates
 ....
27.01.2017 10:51:25 Rename fiskaltrust.service.sqlite 1.0.16326.1233 updates ...
.
27.01.2017 10:51:25 Loading Helper Package fiskaltrust.service.helper.helipad, V
ersion 1.0.16326.1235
27.01.2017 10:51:26 Loading SecureSignaturCreationDevice Id 3b124a67-3ba0-4b62-8
9a6-6033420c5ab1 from Package fiskaltrust.signing.atrustapdu, Version 1.0.16326.
1240
27.01.2017 10:51:27 Create SecureSignaturCreationDevice
PCSC readers:
0 Gemalto USB Smart Card Reader 0
27.01.2017 10:51:28 CardOS_5.3-card found
27.01.2017 10:51:29 Using card with serialnumber 0x25033890
27.01.2017 10:51:32 Adding Endpoint net.pipe://localhost/3b124a67-3ba0-4b62-89a6
-6033420c5ab1
27.01.2017 10:51:34 Loading Queue Id e005a7cf-fc4b-4586-91b3-638a15cb9e53 from P
ackage fiskaltrust.service.sqlite, Version 1.0.16326.1233
27.01.2017 10:51:34 Create Queue
e005a7cf-fc4b-4586-91b3-638a15cb9e53
27.01.2017 10:51:36 Initialize fiskaltrust.service
27.01.2017 10:51:36 fiskaltrust.service.sqlite.worker
27.01.2017 10:51:36 fiskaltrust.service.sqlite.storage
27.01.2017 10:51:40 fiskaltrust.service.sqlite.storage initialized with database
 file C:\ProgramData\fiskaltrust\service\e005a7cf-fc4b-4586-91b3-638a15cb9e53.sq
lite
27.01.2017 10:51:40 deserialize init_ftCashBox
27.01.2017 10:51:41 updating ftCashBox e0eedb80-e96d-490e-b5c0-60420bcaf600
27.01.2017 10:51:41 deserialize init_ftQueue
27.01.2017 10:51:41 insert ftQueue e005a7cf-fc4b-4586-91b3-638a15cb9e53
27.01.2017 10:51:41 deserialize init_ftQueueAT
27.01.2017 10:51:41 insert ftQueueAT e005a7cf-fc4b-4586-91b3-638a15cb9e53
27.01.2017 10:51:41 deserialize init_ftSignaturCreationUnitAT
27.01.2017 10:51:41 insert ftSignaturCreationUnitAT 3b124a67-3ba0-4b62-89a6-6033
420c5ab1
27.01.2017 10:51:41 Queue e005a7cf-fc4b-4586-91b3-638a15cb9e53 fiskaltrust.servi
ce.sqlite.storage initialized
27.01.2017 10:51:41 Initialize AT
27.01.2017 10:51:41 Using database SSCD-List
27.01.2017 10:51:49 SSCD 3b124a67-3ba0-4b62-89a6-6033420c5ab1 connected at net.p
ipe://localhost/3b124a67-3ba0-4b62-89a6-6033420c5ab1. Certificate provider AT1,
serialnumber 0x25033890
27.01.2017 10:51:49 Initialize DE
27.01.2017 10:51:49 Adding Endpoint http://localhost:1200/horn
27.01.2017 10:51:51 fiskaltrust.Service gestartet, Taste drücken zum Beenden ...

**Comment by FritzHajek** [comment]
Hallo,

bitte einfach einen Startbeleg senden. Der erste Beleg der an eine neue Kassa gesendet werden muss ist ein Startbeleg. (Vorsicht mit dem Stopbeleg, dieser beendet die Kassa endgültig.

LG
Fritz Hajek

**Comment by FritzHajek** [comment]
Hallo,

bitte einfach einen Startbeleg (Inbetriebnahmebeleg) senden. Der erste Beleg der an eine neue Kassa gesendet werden muss ist ein Startbeleg. (Vorsicht mit dem Stopbeleg, dieser beendet die Kassa endgültig.

Liebe Grüße
Fritz Hajek

Ing. Fritz Hajek             | Support - Partner
fiskaltrust consulting gmbh  | Bauernmarkt 24, A-1010 Wien | fritz.hajek@fiskaltrust.at<mailto:fritz.hajek@fiskaltrust.at>
www.fiskaltrust.at<http://www.fiskaltrust.at/>           | Office: +43 15 330 330      | Mobile: +43 676 300 5255

FN 411800p | Handelsgericht Wien | ATU68541544 |
Diese Nachricht und allfällige angehängte Dokumente sind vertraulich und nur für den/die Adressaten bestimmt. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. In diesem Fall bitten wir, den Absender zu verständigen und die Information zu vernichten. Für Übermittlungsfehler oder sonstige Irrtümer bei Übermittlung besteht keine Haftung.
The information contained in this e-mail is intended for the named recipients only. It may contain privileged and confidential information, and if you are not the addressee or the person responsible for delivering this to the addressee, you may not copy, distribute or take action in reliance on it. If you have received this e-mail in error, please notify us immediately by returning the original message to the sender by e-mail.

Von: robertza [mailto:notifications@github.com]
Gesendet: Freitag, 27. Jänner 2017 10:57
An: fiskaltrust/interface <interface@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [fiskaltrust/interface] Queue is out of order,it has not been activated! (#3)


hallo
wir haben alles laut doku installiert, beim startet test.cmd bekommen wir auch keine fehler, sobald wir versuchen einen beleg zu erstellen kommt folgende fehlermeldung.
27.01.2017 10:51:58 Queue e005a7cf-fc4b-4586-91b3-638a15cb9e53 is out of order,
it has not been activated!
wo liegt unser problem
anbei die einträge vom test.cmd

C:\Users\Administrator\Downloads\fiskaltrust.service.launcher(21)>"C:\Users\Admi
nistrator\Downloads\fiskaltrust.service.launcher(21)\fiskaltrust" -cashboxid=e0e
edb80-e96d-490e-b5c0-60420bcaf600 -accesstoken=BBnJxfRBFXSgzy5B0Rpx6FBDYqTgiU51
SXw117gZTZwNvNmMCL5Sv+Rs7rRpR9QVw1H9928DRHXEhwFqfpgIjac= -test
27.01.2017 10:51:14 CashBoxId auf "e0eedb80-e96d-490e-b5c0-60420bcaf600" gesetzt

27.01.2017 10:51:14 AccessToken gesetzt
27.01.2017 10:51:14 Try to download configuration
27.01.2017 10:51:16 Downloading fiskaltrust.service.helper.helipad 1.0.16326.123
5 updates ....
27.01.2017 10:51:19 Download done!
27.01.2017 10:51:19 Downloading fiskaltrust.signing.atrustapdu 1.0.16326.1240 up
dates ....
27.01.2017 10:51:21 Download done!
27.01.2017 10:51:21 Downloading fiskaltrust.service.sqlite 1.0.16326.1233 update
s ....
27.01.2017 10:51:25 Download done!
27.01.2017 10:51:25 Rename fiskaltrust.service.helper.helipad 1.0.16326.1235 upd
ates ....
27.01.2017 10:51:25 Rename fiskaltrust.signing.atrustapdu 1.0.16326.1240 updates
....
27.01.2017 10:51:25 Rename fiskaltrust.service.sqlite 1.0.16326.1233 updates ...
.
27.01.2017 10:51:25 Loading Helper Package fiskaltrust.service.helper.helipad, V
ersion 1.0.16326.1235
27.01.2017 10:51:26 Loading SecureSignaturCreationDevice Id 3b124a67-3ba0-4b62-8
9a6-6033420c5ab1 from Package fiskaltrust.signing.atrustapdu, Version 1.0.16326.
1240
27.01.2017 10:51:27 Create SecureSignaturCreationDevice
PCSC readers:
0 Gemalto USB Smart Card Reader 0
27.01.2017 10:51:28 CardOS_5.3-card found
27.01.2017 10:51:29 Using card with serialnumber 0x25033890
27.01.2017 10:51:32 Adding Endpoint net.pipe://localhost/3b124a67-3ba0-4b62-89a6
-6033420c5ab1
27.01.2017 10:51:34 Loading Queue Id e005a7cf-fc4b-4586-91b3-638a15cb9e53 from P
ackage fiskaltrust.service.sqlite, Version 1.0.16326.1233
27.01.2017 10:51:34 Create Queue
e005a7cf-fc4b-4586-91b3-638a15cb9e53
27.01.2017 10:51:36 Initialize fiskaltrust.service
27.01.2017 10:51:36 fiskaltrust.service.sqlite.worker
27.01.2017 10:51:36 fiskaltrust.service.sqlite.storage
27.01.2017 10:51:40 fiskaltrust.service.sqlite.storage initialized with database
file C:\ProgramData\fiskaltrust\service\e005a7cf-fc4b-4586-91b3-638a15cb9e53.sq
lite
27.01.2017 10:51:40 deserialize init_ftCashBox
27.01.2017 10:51:41 updating ftCashBox e0eedb80-e96d-490e-b5c0-60420bcaf600
27.01.2017 10:51:41 deserialize init_ftQueue
27.01.2017 10:51:41 insert ftQueue e005a7cf-fc4b-4586-91b3-638a15cb9e53
27.01.2017 10:51:41 deserialize init_ftQueueAT
27.01.2017 10:51:41 insert ftQueueAT e005a7cf-fc4b-4586-91b3-638a15cb9e53
27.01.2017 10:51:41 deserialize init_ftSignaturCreationUnitAT
27.01.2017 10:51:41 insert ftSignaturCreationUnitAT 3b124a67-3ba0-4b62-89a6-6033
420c5ab1
27.01.2017 10:51:41 Queue e005a7cf-fc4b-4586-91b3-638a15cb9e53 fiskaltrust.servi
ce.sqlite.storage initialized
27.01.2017 10:51:41 Initialize AT
27.01.2017 10:51:41 Using database SSCD-List
27.01.2017 10:51:49 SSCD 3b124a67-3ba0-4b62-89a6-6033420c5ab1 connected at net.p
ipe://localhost/3b124a67-3ba0-4b62-89a6-6033420c5ab1. Certificate provider AT1,
serialnumber 0x25033890
27.01.2017 10:51:49 Initialize DE
27.01.2017 10:51:49 Adding Endpoint http://localhost:1200/horn
27.01.2017 10:51:51 fiskaltrust.Service gestartet, Taste drücken zum Beenden ...

**Comment by robertza** [comment]
hallo hr. hajek
danke funktioniert jetzt
grüsse
robert zaruba

**Comment by FritzHajek** [comment]
☺

Liebe Grüße
Fritz Hajek

Ing. Fritz Hajek             | Support - Partner
fiskaltrust consulting gmbh  | Bauernmarkt 24, A-1010 Wien | fritz.hajek@fiskaltrust.at<mailto:fritz.hajek@fiskaltrust.at>
www.fiskaltrust.at<http://www.fiskaltrust.at/>           | Office: +43 15 330 330      | Mobile: +43 676 300 5255

FN 411800p | Handelsgericht Wien | ATU68541544 |
Diese Nachricht und allfällige angehängte Dokumente sind vertraulich und nur für den/die Adressaten bestimmt. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. In diesem Fall bitten wir, den Absender zu verständigen und die Information zu vernichten. Für Übermittlungsfehler oder sonstige Irrtümer bei Übermittlung besteht keine Haftung.
The information contained in this e-mail is intended for the named recipients only. It may contain privileged and confidential information, and if you are not the addressee or the person responsible for delivering this to the addressee, you may not copy, distribute or take action in reliance on it. If you have received this e-mail in error, please notify us immediately by returning the original message to the sender by e-mail.

Von: robertza [mailto:notifications@github.com]
Gesendet: Freitag, 27. Jänner 2017 20:12
An: fiskaltrust/interface <interface@noreply.github.com>
Cc: Fritz Hajek <fritz.hajek@fiskaltrust.at>; Comment <comment@noreply.github.com>
Betreff: Re: [fiskaltrust/interface] Queue is out of order,it has not been activated! (#3)


hallo hr. hajek
danke funktioniert jetzt
grüsse
robert zaruba
