### ISSUE TITLE
Sorglospaket für Account gültig oder pro CashBox

### ISSUE THREAD

**Issue by engelhuber** [fiskaltrust/interface#4]
Hallo, ich habe über das Portal ein Sorglospaket gekauft und hatte vorher bereits eine CashBox konfiguriert.
Dazu habe ich allerdings nicht den Upgrade Button in der CashBox genutzt sondern bin über den Shop gegangen.
Nun erscheinen zwei CashBoxes. Meine zuvor erstellte und eine neue. Der neuen ist nun das Sorglospaket zugeordnet. Muss ich nun die neue CashBox nutzen oder kann ich auch mit voller Funktionalität die alte nutzen? Zuvor erstellte FON Meldungen wurden erfolgreich übermittelt, so dass davon auszugehen ist dass das Paket für den gesamten Account gilt!?

![2017-03-07 10_20_04-fiskaltrust portal _ kassen](https://cloud.githubusercontent.com/assets/5049692/23650132/591de0a0-0321-11e7-939a-683bb5bc17bd.png)

**Comment by FritzHajek** [comment]
Hallo,

kann ich vielleicht ein direktes Mail mit den Account-Daten bekommen, dann kann ich mir das gerne ansehen.
fritz.hajek@fiskaltrust.at

Liebe Grüße
Fritz Hajek

Ing. Fritz Hajek             | Support - Partner
fiskaltrust consulting gmbh  | Bauernmarkt 24, A-1010 Wien | fritz.hajek@fiskaltrust.at<mailto:fritz.hajek@fiskaltrust.at>
www.fiskaltrust.at<http://www.fiskaltrust.at/>           | Office: +43 15 330 330      | Mobile: +43 676 300 5255

FN 411800p | Handelsgericht Wien | ATU68541544 |
Diese Nachricht und allfällige angehängte Dokumente sind vertraulich und nur für den/die Adressaten bestimmt. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. In diesem Fall bitten wir, den Absender zu verständigen und die Information zu vernichten. Für Übermittlungsfehler oder sonstige Irrtümer bei Übermittlung besteht keine Haftung.
The information contained in this e-mail is intended for the named recipients only. It may contain privileged and confidential information, and if you are not the addressee or the person responsible for delivering this to the addressee, you may not copy, distribute or take action in reliance on it. If you have received this e-mail in error, please notify us immediately by returning the original message to the sender by e-mail.

Von: engelhuber [mailto:notifications@github.com]
Gesendet: Dienstag, 7. März 2017 10:34
An: fiskaltrust/interface <interface@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [fiskaltrust/interface] Sorglospaket für Account gültig oder pro CashBox (#4)


Hallo, ich habe über das Portal ein Sorglospaket gekauft und hatte vorher bereits eine CashBox konfiguriert.
Dazu habe ich allerdings nicht den Upgrade Button in der CashBox genutzt sondern bin über den Shop gegangen.
Nun erscheinen zwei CashBoxes. Meine zuvor erstellte und eine neue. Der neuen ist nun das Sorglospaket zugeordnet. Muss ich nun die neue CashBox nutzen oder kann ich auch mit voller Funktionalität die alte nutzen? Zuvor erstellte FON Meldungen wurden erfolgreich übermittelt, so dass davon auszugehen ist dass das Paket für den gesamten Account gilt!?

[2017-03-07 10_20_04-fiskaltrust portal _ kassen]<https://cloud.githubusercontent.com/assets/5049692/23650132/591de0a0-0321-11e7-939a-683bb5bc17bd.png>

**Comment by fiskaltrust** [comment]
Hallo Fritz, ich denk er hat vorher eine Cashbox hergestellt (1).
Dann hat er im Shop das Template mit sorglos ausgewählt und ausgecheckt, somit hat er eine neue Cashbox mit aktiviertem Sorglos Paket bekommen.
Ich würd sagen die erste kann er einfach verwerfen/ignorieren.
LG

**Comment by engelhuber** [comment]
Mail ist raus
